FROM python:3.11
WORKDIR /app
COPY backend/ /app
RUN pip install -r requirements.txt

# Gunicorn'u debug modunda çalıştırarak daha detaylı log almasını sağlıyoruz
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--log-level", "debug", "flask_app.app:app"]
